library(XML)
library(data.table)
library(xts)

# Sources are "http://www.federalreserve.gov/releases/h10/hist/dat00_mx.htm" and "http://www.federalreserve.gov/releases/h10/hist/dat96_mx.htm")
# sources <- c("2016.csv", "1999.csv")
usd_mxn <- read.csv("usdmxn.csv", stringsAsFactors = FALSE, strip.white=TRUE)
usd_mxn$Date <- as.Date(usd_mxn$Date, "%m/%d/%Y")
summary(usd_mxn)
ts <- xts(usd_mxn$Rate, usd_mxn$Date)
plot(ts)
